[package]
name = "exec-suid"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = "symbols"

[dependencies]
nix = { version = "0.29", features = ["fs", "process", "user"] }
