name: Test and Release

on: push

jobs:
  build-test-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and test
      run: |
        docker build -t exec-suid .
        docker run --name exec-suid exec-suid
        docker cp exec-suid:/usr/bin/exec-suid ./exec-suid

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ./exec-suid
